### PR TITLE
feat: rewrite generator, add version override interface

### PR DESCRIPTION
**Pull request by nderscore**
As previously discussed in #2 - here's a first pass at attempting to rewrite the code generation using plist resources from the SF Symbols desktop application as the source of truth.

It does not currently implement the "restricted symbols" feature that existed previously. I was unfortunately not able to find that metadata anywhere easily accessible. 😖 

I chose to ignore it for now, since those JSDoc comments were never really exposed by the IDE anyway. If this feature is still considered valuable, we could probably keep the existing JSON list around and it could be manually maintained.

## Instructions to regenerate

Assuming you have the [SF Symbols desktop application](https://developer.apple.com/sf-symbols/) installed...

Open its package contents

image

Navigate to `./Contents/Resources/Metadata`

Copy `name_availability.plist` from this directory into the `sf-symbols-typescript` `src/data` folder.

Then run the generator script (`bun run build`)

### CODE REVIEW

**Comment by nandorojo** [comment]
Would you mind updating the docs with any relevant info? Nice PR!

**Comment by nderscore** [comment]
Just pushed a quick update to this.

I replaced the years-based versioning (which seem to only be referenced internally by the SF Symbols app) with the public versions numbers of SF Symbols.

I also I dug up some [prior art from the Swift world](https://github.com/SFSafeSymbols/SFSafeSymbols). They've got the same plist files I used here checked into their repository (albiet not up to date with SF Symbols 5 yet at the time of this writing) - might be a good alternative means of getting the SF Symbols plist files.

> Would you mind updating the docs with any relevant info? Nice PR!

Sure thing 👍

**Comment by nderscore** [comment]
Added some docs. 

Let me know if you're okay with the changes and/or wording, especially around the "credits" section

**Comment by nandorojo** [comment]
@nderscore i don't have too much time to review it all, but i can just trust you and merge/release this. are there no breaking changes?

**Comment by nderscore** [comment]
@nandorojo I'm pretty confident that this should be compatible with existing usages.

Using the `Overrides` interface feature is optional - the main type export will include all icons for SF Symbols 5 with the default setting.

It might be worth considering updating the docs of consumer libs (zeego / burnt) after publishing this change. Something to guide users whose apps target older iOS versions toward instructions on adding the override, so that people don't accidentally use icon names from SF Symbols v5 where they aren't supported. Probably a link to that section of this repository's readme would be sufficient?

**Pull request merged**
